server.port: 8888
server.use-forward-headers: true
server.servlet.context-path: /toy

server:
  servlet:
    session:
      timeout: 86400
  tomcat:
    max-connections: 10000
    max-threads: 200

spring:
  application:
    name: gmul-toy
  http:
    log-request-details: false
  thymeleaf:
    cache: false
  session:
    store-type: REDIS
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.generate_statistics: false
    open-in-view: false
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/example_db?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      maximum-pool-size: 3
  main:
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
